-- INVOICES TABLE (Storage & Audit Trail)
CREATE TABLE invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  vendor_name TEXT NOT NULL,
  invoice_number TEXT NOT NULL,
  amount NUMERIC(15, 2) NOT NULL,
  invoice_hash TEXT UNIQUE NOT NULL, -- Deterministic fingerprint: sha256(vendor|invoice_num|amount)
  status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_REVIEW')),
  confidence_score NUMERIC(3, 2) DEFAULT 0.00,
  raw_text TEXT,
  file_url TEXT
);

-- AI DECISIONS TABLE (Explainability Log)
CREATE TABLE ai_decisions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  invoice_id BIGINT REFERENCES invoices(id) ON DELETE CASCADE,
  decision TEXT NOT NULL CHECK (decision IN ('APPROVED', 'REJECTED', 'NEEDS_REVIEW')),
  confidence_score NUMERIC(3, 2) NOT NULL,
  reason TEXT, -- Comma-separated or JSON list of flags e.g. "UNKNOWN_VENDOR, DUPLICATE_INVOICE"
  metadata JSONB DEFAULT '{}'::JSONB
);

-- VENDORS TABLE (Trusted Verification Source)
CREATE TABLE vendors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  company_name TEXT UNIQUE NOT NULL,
  email_contact TEXT,
  trust_score INT DEFAULT 50 CHECK (trust_score BETWEEN 0 AND 100),
  status TEXT DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'BLOCKED', 'REVIEW'))
);

-- OPTIONAL: Create indexes for performance
CREATE INDEX idx_invoices_hash ON invoices(invoice_hash);
CREATE INDEX idx_vendors_name ON vendors(company_name);
